### ISSUE TITLE
hal2mafMP.py modulenotfounderror sonLib.bioio

### ISSUE THREAD

**Issue by taylorjtamu** [ComparativeGenomicsToolkit/hal#129]
I compiled hal for some of our researchers a few days ago on one of our Scientific Linux 7 machines. They've reported that it's working mostly correctly, but that when they try to run hal2mafMP.py it gives the error below.

```
Traceback (most recent call last):

  File "/software/hal/bin/hal2mafMP.py", line 19, in <module>

    from sonLib.bioio import system

ModuleNotFoundError: No module named 'sonLib.bioio'
```

I had them try adding the sonLib path to their PATH just in case, but it didn't have any effect. I also checked sonLib itself and did find a bioio file. At this point I'm not familiar enough with these packages to know how to deeply diagnose this. Let me know if I need to provide additional information.

**Comment by diekhans** [comment]
you will need to setup a Python 3.6+ virtualenv and then

pip install xxxx/sonLib

**Comment by minjinhan** [comment]
Dear Mark Diekhans, 

I encountered the same problem (No module named 'sonLib.bioio').  According to your suggestion, we setup Python 3.6+ virtualenv and pip install sonLib.  Finally, sonLib-1.1.0 was successfully installed in our server (centos6.5). But when we run halPhyloPTrain.py again, there are new errors as follows:

Traceback (most recent call last):
  File "./hal/bin/hal2mafMP.py", line 19, in <module> from sonLib.bioio import system
  File "./python3.6/site-packages/sonLib/bioio.py", line 431 os.chmod(dirName, 0777)

SyntaxError: invalid token
Traceback (most recent call last):
  File "./hal/bin/halPhyloPTrain.py", line 260, in <module> sys.exit(main())
  File "./hal/bin/halPhyloPTrain.py", line 257, in main computeModel(args)
  File "./hal/bin/halPhyloPTrain.py", line 133, in computeModel extractGeneMAFs(options)
  File "./hal/bin/halPhyloPTrain.py", line 60, in extractGeneMAFs bedFile4d, options.refGenome))
  File "./hal/hal/stats/halStats.py", line 28, in runShellCommand   (command, sts))
RuntimeError: Command: hal2mafMP.py evolver.hal .....  exited with non-zero status 1

Can you supply some suggestions to fix this error? 

Thanks!

**Comment by crinfante** [comment]
I'm also having this problem with hal2assemblyHub.py after installing hal and dependencies following the guide:
`
Traceback (most recent call last):
  File "./hal2assemblyHub.py", line 24, in <module>
    from sonLib.bioio import system, getTempFile
ModuleNotFoundError: No module named 'sonLib.bioio'
`
As suggested above, I've created a conda environment with Python=3.6 and installed sonLib via pip:
`
conda install python=3.6 pip
pip install sonLib
`
I still get an error, but now it is a syntax error:
`
Traceback (most recent call last):
  File "/projects/$USER/src/hal-tools/hal/bin/hal2assemblyHub.py", line 24, in <module>
    from sonLib.bioio import system, getTempFile
  File "/projects/$USER/miniconda3/envs/hal-tools/lib/python3.6/site-packages/sonLib/bioio.py", line 431
    os.chmod(dirName, 0777)
                         ^
SyntaxError: invalid token
`
If the sonLib available via pip is not Python 3.6 compatible, how can I solve this problem?

Thanks!

**Comment by diekhans** [comment]
This is fixed in git.  I would suggest getting the lastes cactus binary release, which
include hal
