### ISSUE TITLE
halPhyloPTrain error

### ISSUE THREAD

**Issue by minjinhan** [ComparativeGenomicsToolkit/hal#184]
Hello guys,

We encountered the same problem with #129 (No module named 'sonLib.bioio'). According to the suggestion, we setup Python 3.6+ virtualenv and pip install sonLib. Finally, sonLib-1.1.0 was successfully installed in our server (centos6.5). But when we run halPhyloPTrain.py again, there are new errors as follows:

Traceback (most recent call last):
File "./hal/bin/hal2mafMP.py", line 19, in from sonLib.bioio import system
File "./python3.6/site-packages/sonLib/bioio.py", line 431 os.chmod(dirName, 0777)

SyntaxError: invalid token
Traceback (most recent call last):
File "./hal/bin/halPhyloPTrain.py", line 260, in sys.exit(main())
File "./hal/bin/halPhyloPTrain.py", line 257, in main computeModel(args)
File "./hal/bin/halPhyloPTrain.py", line 133, in computeModel extractGeneMAFs(options)
File "./hal/bin/halPhyloPTrain.py", line 60, in extractGeneMAFs bedFile4d, options.refGenome))
File "./hal/hal/stats/halStats.py", line 28, in runShellCommand (command, sts))
RuntimeError: Command: hal2mafMP.py evolver.hal ..... exited with non-zero status 1

Anybody can help me to fix this error?

Thanks!

**Comment by diekhans** [comment]
It looks like you have a python 2.7 version of sonlib.
The current code uses python 3 syntax of:

       os.chmod(dirName, 0o777)

**Comment by minjinhan** [comment]
@diekhans Thanks for your suggestion. We have solved that problem.
