### ISSUE TITLE
hal2assemblyHub.py Invalid tree error when computing conservation tracks

### ISSUE THREAD

**Issue by alexgilgal** [ComparativeGenomicsToolkit/hal#188]
Hi!

Im using the tool hal2assemblyHub in order to transform a hal alignment produced with Cactus. I also want to get the conservation track for the Hub. Everything computes as normal until it reaches the part that halPhyloPTrain.py has to execute. I got this error:

```
Job failed with exit value 1: 'GetConservationFiles' kind-GetConservationFiles/instance-3mpdddi5
The job seems to have left a log file, indicating failure: 'GetConservationFiles' kind-GetConservationFil
es/instance-3mpdddi5
Log from job kind-GetConservationFiles/instance-3mpdddi5 follows:
=========>
        [2021-01-18T11:16:44+0100] [MainThread] [I] [toil.worker] ---TOIL WORKER OUTPUT LOG---
        [2021-01-18T11:16:44+0100] [MainThread] [I] [toil] Running Toil version 4.2.0-3aa1da130141039cb357efe36d7df9b9f6ae9b5b on host ******
        Reading alignment from /home/agilgal/Cave_surface_hub/Cave_vs_SF_hub_with_cons/conservation/AstMex_Surface_halPhyloPTrain_temp_VHXOKEN_AstMex_Surface_halPhyloPTrain_temp_VHXOKEN_Genes_astmex_surface4d.maf ...
        Invalid treeTraceback (most recent call last):
          File "/home/agilgal/bin/hal/bin/halPhyloPTrain.py", line 260, in <module>
            sys.exit(main())
          File "/home/agilgal/bin/hal/bin/halPhyloPTrain.py", line 257, in main
            computeModel(args)
          File "/home/agilgal/bin/hal/bin/halPhyloPTrain.py", line 135, in computeModel
            computeFit(options)
          File "/home/agilgal/bin/hal/bin/halPhyloPTrain.py", line 116, in computeFit
            runShellCommand(cmd)
          File "/home/agilgal/cactus-bin-v1.2.3/lib/hal/stats/halStats.py", line 28, in runShellCommand
            (command, sts))
        RuntimeError: Command: phyloFit --tree "((AstMex_Surface:1,AstMex_Pachon:1)Anc1:1)Anc0;" --subst-mod SSREV --sym-freqs /home/agilgal/Cave_surface_hub/Cave_vs_SF_hub_with_cons/conservation/AstMex_Surface_halPhyloPTrain_temp_VHXOKEN.ss --precision MED --out-root /home/agilgal/Cave_surface_hub/Cave_vs_SF_hub_with_cons/conservation/AstMex_Surface exited with non-zero status 1
        Traceback (most recent call last):
          File "/home/agilgal/miniconda3/envs/cactus_local/lib/python3.6/site-packages/toil/worker.py", line 368, in workerScript
            job._runner(jobGraph=jobGraph, jobStore=jobStore, fileStore=fileStore, defer=defer)
          File "/home/agilgal/miniconda3/envs/cactus_local/lib/python3.6/site-packages/toil/job.py", line 1424, in _runner
            returnValues = self._run(jobGraph, fileStore)
          File "/home/agilgal/miniconda3/envs/cactus_local/lib/python3.6/site-packages/toil/job.py", line 1361, in _run
            return self.run(fileStore)
          File "/home/agilgal/cactus-bin-v1.2.3/lib/hal/assemblyHub/conservationTrack.py", line 33, in run
            system(cmd)
          File "/home/agilgal/miniconda3/envs/cactus_local/lib/python3.6/site-packages/sonLib/bioio.py", line 194, in system
            raise RuntimeError("Command: %s exited with non-zero status %i" % (command, sts))
        RuntimeError: Command: halPhyloPTrain.py /home/agilgal/Cave_surface_hub/Cave_vs_Surface.hal AstMex_Surface /home/agilgal/Cave_surface_hub/Genes_astmex_surface.bed /home/agilgal/Cave_surface_hub/Cave_vs_SF_hub_with_cons/conservation/AstMex_Surface.mod --numProc 24 exited with non-zero status 1
        [2021-01-18T11:19:38+0100] [MainThread] [E] [toil.worker] Exiting the worker because of a failed job on host *****
<=========

```
The problem comes when phyloFit throws the error Invalid tree. Have you experienced this kind of error before? this is the command that i have used:

```
hal2assemblyHub.py --maxCores 24 --lod --lodInMemory --logFile logs/hal2assembly_conservation.log --conservation /home/agilgal/Cave_surface_hub/Genes_astmex_surface.bed --conservationGenomeName AstMex_Surface --conservationNumProc 24 --workDir /home/agilgal/tmp /mnt/beegfs/agilgal/Cave_vs_surface_hub/jobstore_cons Cave_vs_Surface.hal Cave_vs_SF_hub_with_cons/
```
Thanks a lot.

**Comment by alexgilgal** [comment]
I have found the problem. The tree that the HAL stores has singletons, which makes the Phast software complain. You can clean the tree of singleton using the R package ape with the function ape::collapse.singles(tree).
Now the bw file with Phast scres is produced.
