### ISSUE TITLE
hal2assemblyHub.py/treeCommon.py inorder fails on unary trees

### ISSUE THREAD

**Issue by adamnovak** [ComparativeGenomicsToolkit/hal#19]
It's difficult to tell if hal2assemblyHub is supposed to support non-binary trees or not; it complains at runtime that it doesn't, but it tries to continue anyway, and the last commit message on treeCommon.py is about supporting non-binary trees.

Anyway, when I have a HAL consisting of a single ancestor and a single descendant, and I want to create an assembly hub for it, it fails:

```
The job seems to have left a log file, indicating failure: /cluster/home/anovak/hive/sgdev/mhc/tree2/jobs/t1/job
Reporting file: /cluster/home/anovak/hive/sgdev/mhc/tree2/jobs/t1/log.txt
log.txt:        ---JOBTREE SLAVE OUTPUT LOG---
log.txt:        Tree refmhc is not a binary tree format! Binary tree is required. Please check.
log.txt:        Traceback (most recent call last):
log.txt:          File "/cluster/home/anovak/.local/lib/python2.7/site-packages/jobTree-1.0-py2.7.egg/jobTree/src/jobTreeSlave.py", line 271, in main
log.txt:            defaultMemory=defaultMemory, defaultCpu=defaultCpu, depth=depth)
log.txt:          File "/cluster/home/anovak/.local/lib/python2.7/site-packages/jobTree-1.0-py2.7.egg/jobTree/scriptTree/stack.py", line 153, in execute
log.txt:            self.target.run()
log.txt:          File "/hive/users/anovak/build/progressiveCactus/submodules/hal/assemblyHub/hal2assemblyHub.py", line 299, in run
log.txt:            subgenomes = getNeighbors(self.options.tree, currgenome)
log.txt:          File "/hive/users/anovak/build/progressiveCactus/submodules/hal/assemblyHub/treeCommon.py", line 121, in getNeighbors
log.txt:            allSortedNames = inorder_relative(tree, name)
log.txt:          File "/hive/users/anovak/build/progressiveCactus/submodules/hal/assemblyHub/treeCommon.py", line 74, in inorder_relative
log.txt:            return inorder(newtree.root)
log.txt:          File "/hive/users/anovak/build/progressiveCactus/submodules/hal/assemblyHub/treeCommon.py", line 46, in inorder
log.txt:            left, right = getLeftRight(children)
log.txt:          File "/hive/users/anovak/build/progressiveCactus/submodules/hal/assemblyHub/treeCommon.py", line 30, in getLeftRight
log.txt:            count1 = children[1].count_terminals()
log.txt:        IndexError: list index out of range
log.txt:        Exiting the slave because of a failed job on host ku.sdsc.edu
log.txt:        Due to failure we are reducing the remaining retry count of job /cluster/home/anovak/hive/sgdev/mhc/tree2/jobs/t1/job to 0
log.txt:        We have set the default memory of the failed job to 2147483648 bytes
Job: /cluster/home/anovak/hive/sgdev/mhc/tree2/jobs/t1/job is completely failed
Traceback (most recent call last):
  File "/cluster/home/anovak/hive/build/progressiveCactus/submodules/hal/bin/hal2assemblyHub.py", line 450, in <module>
    main()
  File "/hive/users/anovak/build/progressiveCactus/submodules/hal/assemblyHub/hal2assemblyHub.py", line 446, in main
    raise RuntimeError("The jobtree contains %d failed jobs.\n" %i)
RuntimeError: The jobtree contains 1 failed jobs.

```

It looks like getLeftRight assumes every node has at least two children. Since there seems to be at least some effort to support non-binary trees, it shouldn't do that.

**Comment by adamnovak** [comment]
This bug came back to bother me again today. I would really like to be able to look at non-binary HALs in the browser.
