### ISSUE TITLE
RuntimeError: singleMachine is the only supported batchSystem

### ISSUE THREAD

**Issue by saoirseguita** [ComparativeGenomicsToolkit/hal#199]
Hi, I'm receiving the error as stated in the title when running hal2assemblyHub.py as follows via slurm: 

hal2assemblyHub.py --batchSystem slurm --lod --lodInMemory --alignability --logFile ./log.txt-$SLURM_JOBID ./jobstoreHAL ./mga.hal ./HALoutDir/

I'd greatly appreciate any insights as to what needs to be done to fix this. 

Also, not sure if this is an issue with my installation or not, but the [manual](https://github.com/ComparativeGenomicsToolkit/hal/tree/master/assemblyHub#comparative-assembly-hub-manual) appears to have some slightly outdated information. Notably, it does not specify that a jobstore needs to be passed to the command. The --maxThreads option also cannot be invoked despite it being used in examples.

**Comment by glennhickey** [comment]
I think the story here is something like this. `hal2assemblyHub.py` was originally written to use [JobTree](https://github.com/benedictpaten/jobTree). But when Cactus/HAL were ported to Python3, all JobTree code stopped working.  People (reasonably) complained, so I hastily patched up `hal2assemblyHub.py` so that it would use JobTree's successor, [Toil](https://github.com/DataBiosphere/toil) instead.  I added that "singleMachine" only message because I didn't take the time to ensure everything was working with Toil's more abstract file handling model that allows it to work on all sorts of distributed environments.

That said... it may work on other batchSystems provided they use a shared local file system for the jobstore, so maybe that message is too pessimistic.  You can test this by commenting it out and rerunning.

**Comment by saoirseguita** [comment]
Many thanks for the explanation. 

My resources only have access to SLURM. I have tried commenting out lines 416-420 in the hals2assemblyHub.py script, but unfortunately the same error is returned. 

I notice that the script is actually bundled with Cactus too (i.e. there may not be a need to download HAL to access this file as it seems to come with Cactus); perhaps this is a different version of the script that may be more amenable to running under these circumstances?

**Comment by saoirseguita** [comment]
Update: even running the following without SLURM yields the same error. I did not specify a batch system here. 


```
(conda_env)$ hal2assemblyHub.py --lod --lodInMemory --alignability --logFile ./log.txt-$SLURM_JOBID ./jobstoreHAL ./mga.hal ./HALoutDir/
Traceback (most recent call last):
  File "/ocean/projects/mcb200013p/sfoley/HAL/hal/bin/hal2assemblyHub.py", line 450, in <module>
    main()
  File "/ocean/projects/mcb200013p/sfoley/HAL/hal/assemblyHub/hal2assemblyHub.py", line 443, in main
    checkOptions(parser, options)
  File "/ocean/projects/mcb200013p/sfoley/HAL/hal/assemblyHub/hal2assemblyHub.py", line 419, in checkOptions
    raise RuntimeError("singleMachine is the only supported batchSystem")
RuntimeError: singleMachine is the only supported batchSystem
```
