### ISSUE TITLE
halPhyloPTrain can't run phyloFit

### ISSUE THREAD

**Issue by RenzoTale88** [ComparativeGenomicsToolkit/hal#223]
Hi, I'm trying to run halPhyloPTrain on an hal archive I've generated using cactus v1.3.0. The code start without any issues, just crash with the following error:
```
Command error:
  Reading alignment from neutralModel_halPhyloPTrain_temp_JVJSPUL_neutralModel_halPhyloPTrain_temp_JVJSPUL_neutralRegions4d.maf ...
  Invalid treeTraceback (most recent call last):
    File "cactus/bin/halPhyloPTrain.py", line 260, in <module>
      sys.exit(main())
    File "cactus/bin/halPhyloPTrain.py", line 257, in main
      computeModel(args)
    File "cactus/bin/halPhyloPTrain.py", line 135, in computeModel
      computeFit(options)
    File "cactus/bin/halPhyloPTrain.py", line 116, in computeFit
      runShellCommand(cmd)
    File "cactus/lib/hal/stats/halStats.py", line 27, in runShellCommand
      raise RuntimeError("Command: %s exited with non-zero status %i" %
  RuntimeError: Command: phyloFit --tree "((genome1:0.07928,(((genome2:0.0049,(((genome3:0.0016,genome4:0.0016)Inner3:0.00024,((genome5:0.00143,genome6:0.00143)Inner1:0.00022,genome7:0.00165)Inner4:0.00019)Inner5:0.00141,genome8:0.00306)Inner9:0.00184)Inner10:0.01431,genome9:0.01921)Inner14:0.01992,((genome10:0.00612,(genome11:0.00287,(genome12:0.00256,(genome13:0.00193,(genome14:0.00151,genome15:0.00151)Inner2:0.00042)Inner6:0.00063)Inner7:0.00031)Inner8:0.00325)Inner11:0.01031,(genome16:0.01089,genome17:0.01089)Inner12:0.00555)Inner13:0.02824)Inner15:0.06007)Inner16:0)Anc00;" --subst-mod SSREV --sym-freqs neutralModel_halPhyloPTrain_temp_JVJSPUL.ss --precision MED --out-root neutralModel exited with non-zero status 1
```

When I try to run the command that fails myself, I get the following error:
```
Invalid tree
```

Any idea if it is possible to fix this?

Thank you in advance
Andrea

**Comment by francicco** [comment]
Hi Renzo,

For what I understood the tree you give witht --tree needs to contain the same genome, and ancestral genome names, than the one from the hal file. Basically it needs to have the same topology.

I hope I was helpful. btw, I'm a user too and struggling to make these scripts to work.
Cheers
F
