### ISSUE TITLE
faToTwoBit: error while loading shared libraries: libkrb5.so.3

### ISSUE THREAD

**Issue by dylansosa** [ComparativeGenomicsToolkit/hal#245]
Dear all,

I am attempting to use `hal2assemblyHub.py` so that I can perform a synteny analysis of the aligned genomes of the species I am working with. I have encountered an error, pasted below, that seems to point out that I am missing `libkrb5.so.3:`. However, I see this library is indeed in my `~/anaconda3/lib`! I'm not sure if there is somewhere else this library should be installed or if I need to do something more to be able to fully use `hal2assemblyHub.py`. The script does produce the genome assembly directories, groups.txt, hub.txt, and two newick trees before quickly halting.

Any insights would be appreciated! Also, if there is a preferred way to visualize synteny with the cactus output please let me know!

My command: `hal2assemblyHub.py jobStore drosophilaSpecies.hal assemblyHub --lod`

Dylan

```
[2022-07-08T07:33:44+0800] [MainThread] [W] [toil.leader] Job failed with exit value 1: 'GetBasicFiles' kind-GetBasicFiles/i
nstance-zuhfrkhs                                                                                                            
[2022-07-08T07:33:44+0800] [MainThread] [W] [toil.leader] The job seems to have left a log file, indicating failure: 'GetBas
icFiles' kind-GetBasicFiles/instance-zuhfrkhs                                                                               
[2022-07-08T07:33:44+0800] [MainThread] [W] [toil.leader] Log from job kind-GetBasicFiles/instance-zuhfrkhs follows:        
=========>                                                                                                                  
        [2022-07-08T07:33:42+0800] [MainThread] [I] [toil.worker] ---TOIL WORKER OUTPUT LOG---                              
        [2022-07-08T07:33:42+0800] [MainThread] [I] [toil] Running Toil version 5.0.0-f182c6420554b258632a40bfa47a8f69e56675
e4 on host yakuba.                                                                                                          
        [2022-07-08T07:33:42+0800] [MainThread] [I] [toil.worker] Working on job 'GetBasicFiles' kind-GetBasicFiles/instance
-zuhfrkhs                                                                                                                   
        [2022-07-08T07:33:42+0800] [MainThread] [I] [toil.worker] Loaded body Job('GetBasicFiles' kind-GetBasicFiles/instanc
e-zuhfrkhs) from description 'GetBasicFiles' kind-GetBasicFiles/instance-zuhfrkhs                                           
        faToTwoBit: error while loading shared libraries: libkrb5.so.3: cannot open shared object file: No such file or dire
ctory                                                                                                                       
        Traceback (most recent call last):                                                                                  
          File "/home/sosa/anaconda3/envs/binf/lib/python3.8/site-packages/toil/worker.py", line 393, in workerScript       
            job._runner(jobGraph=None, jobStore=jobStore, fileStore=fileStore, defer=defer)                                 
          File "/home/sosa/anaconda3/envs/binf/lib/python3.8/site-packages/toil/job.py", line 2358, in _runner              
            returnValues = self._run(jobGraph=None, fileStore=fileStore)                                                    
          File "/home/sosa/anaconda3/envs/binf/lib/python3.8/site-packages/toil/job.py", line 2279, in _run                 
            return self.run(fileStore)                                                                                      
          File "/home/sosa/software/cactus-bin-v2.1.0/bin/hal2assemblyHub.py", line 121, in run                             
            self.makeTwoBitSeqFile(genomedir) #genomedir/genome.2bit                                                        
          File "/home/sosa/software/cactus-bin-v2.1.0/bin/hal2assemblyHub.py", line 144, in makeTwoBitSeqFile               
            system("faToTwoBit %s %s" %(fafile2, twobitfile))                                                               
          File "/home/sosa/anaconda3/envs/binf/lib/python3.8/site-packages/sonLib/bioio.py", line 194, in system            
            raise RuntimeError("Command: %s exited with non-zero status %i" % (command, sts))                               
        RuntimeError: Command: faToTwoBit /home/sosa/thesis/3_tRNA_evolution/cactus/assemblyHub/15/15.fa /home/sosa/thesis/3
_tRNA_evolution/cactus/assemblyHub/15/15.2bit exited with non-zero status 127                                               
        [2022-07-08T07:33:44+0800] [MainThread] [E] [toil.worker] Exiting the worker because of a failed job on host yakuba 
<=========                                                                                                                  
```

**Comment by diekhans** [comment]
Your are missing libkrb5.so.3, which is the Kerberos 5 library.

This is in the krb5 anaconda package

>         faToTwoBit: error while loading shared libraries: libkrb5.so.3: cannot open shared object file: No such file or directory

**Comment by dylansosa** [comment]
> Your are missing libkrb5.so.3, which is the Kerberos 5 library. This is in the krb5 anaconda package
> […](#)

Hi Mark,

Thanks for replying! I previously did have krb5 installed, and I confirmed with `conda install -c anaconda krb5`. I am working in `cactus_env` and also tried to install with pip3, but I still have the same error that libkrb5.so.3 cannot be found. Is there a more correct way to install krb5?
