### ISSUE TITLE
Help with halPhyloPTrain.py

### ISSUE THREAD

**Issue by xiaoyezao** [ComparativeGenomicsToolkit/hal#274]
Hello, I got the following error with halPhyloPTrain.py. Can you please help to debug this?

halPhyloPTrain.py $hal_file $reference $neutralRegions.bed $neutralModel.mod --numProc 12
```
Reading alignment from Lactuca_neutralModel_halPhyloPTrain_temp_NADOHCS_Lactuca_neutralModel_halPhyloPTrain_temp_NADOHCS_Lsat_1_Genome_v11.01.annotation_Maker.gff.tidy.chr8.4d4d.maf ...
ERROR msa_reorder_rows: covered[new_to_old[5]]=1 should be 0
Traceback (most recent call last):
  File "/home/CBS2021/app/cactus-bin-v2.5.2/bin/halPhyloPTrain.py", line 260, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/CBS2021/app/cactus-bin-v2.5.2/bin/halPhyloPTrain.py", line 257, in main
    computeModel(args)
  File "/home/CBS2021/app/cactus-bin-v2.5.2/bin/halPhyloPTrain.py", line 134, in computeModel
    computeAgMAFStats(options)
  File "/home/CBS2021/app/cactus-bin-v2.5.2/bin/halPhyloPTrain.py", line 103, in computeAgMAFStats
    runShellCommand("msa_view -o SS -z --in-format MAF --aggregate %s %s > %s" % (
  File "/home/CBS2021/app/cactus-bin-v2.5.2/lib/hal/stats/halStats.py", line 27, in runShellCommand
    raise RuntimeError("Command: %s exited with non-zero status %i" %
RuntimeError: Command: msa_view -o SS -z --in-format MAF --aggregate Anc0,T.koksaghyz,Anc1,L.virosa,Anc2,L.saligna,Anc3,L.serriola,L.sativa Lactuca_neutralModel_halPhyloPTrain_temp_NADOHCS*.maf > Lactuca_neutralModel_halPhyloPTrain_temp_NADOHCS.ss exited with non-zero status 1
```

The head of the intermediate *.maf file is:
```
##maf version=1 scoring=N/A

a
s       L.sativa.Lsat_1_v11_chr8        94777886        1       +       343517054       T
s       Anc0.Anc0refChr3        163905  1       +       189369  T
s       Anc1.Anc1refChr1593     44277   1       +       81021   T
s       Anc2.Anc2refChr2805     62794   1       -       240409  T
s       Anc3.Anc3refChr2040     413548  1       +       2493988 T
s       L.saligna.chr8  142086748       1       -       238633233       T
s       L.serriola.Lser_1_US96UC23_v10_chr8     93752352        1       +       329941051       T
s       L.virosa.Lvir_CGN04683_V4_scf4  186602678       1       -       342977835       T
s       T.koksaghyz.GWHBCHF00000009     5976022 1       +       111408619       T

a
s       L.sativa.Lsat_1_v11_chr8        94777904        1       +       343517054       T
s       Anc0.Anc0refChr3        163923  1       +       189369  T
s       Anc1.Anc1refChr1593     44295   1       +       81021   T
s       Anc2.Anc2refChr2805     62812   1       -       240409  T
s       Anc3.Anc3refChr2040     413566  1       +       2493988 T
s       L.saligna.chr8  142086766       1       -       238633233       T
s       L.serriola.Lser_1_US96UC23_v10_chr8     93752370        1       +       329941051       T
s       L.virosa.Lvir_CGN04683_V4_scf4  186602696       1       -       342977835       T
s       T.koksaghyz.GWHBCHF00000009     5976040 1       +       111408619       T

a
s       L.sativa.Lsat_1_v11_chr8        94777919        1       +       343517054       C
s       Anc0.Anc0refChr3        163938  1       +       189369  C
s       Anc1.Anc1refChr1593     44310   1       +       81021   C
s       Anc2.Anc2refChr2805     62827   1       -       240409  C
s       Anc3.Anc3refChr2040     413581  1       +       2493988 C
s       L.saligna.chr8  142086781       1       -       238633233       C
s       L.serriola.Lser_1_US96UC23_v10_chr8     93752385        1       +       329941051       C
s       L.virosa.Lvir_CGN04683_V4_scf4  186602711       1       -       342977835       C
s       T.koksaghyz.GWHBCHF00000009     5976055 1       +       111408619       C
```

**Comment by George-du** [comment]
Hi, I want to do something similar, so the first step is to use _**cactus-hal2maf --dupeMode single**_ to export a single-copy maf, but it generates the following error message, how should I solve the problem.


cactus-hal2maf  js  --workDir  work --maxCores 5 --dupeMode single mc.full.hal  mc.full.maf  --chunkSize 1000000   --refGenome Chimpanzee

<img width="960" alt="image" src="https://github.com/ComparativeGenomicsToolkit/hal/assets/26595839/fe653677-de7e-4d71-8663-0f7446a41def">

**Comment by George-du** [comment]
Hi, are there any suggestions? I'm looking forward for your reply.

**Comment by glennhickey** [comment]
Please share your full log.

**Comment by glennhickey** [comment]
Sorry, I can't really make that out.  I've had some problems with `--restart` in the past. I'm guessing that's what's at issue here (the `--restart` option).  I will just say that `--chunkSize 3` is way too small and will certainly not help.  If, say, you are working on a human alignment, then that will ask it to make ~1,000,000,000 `hal2maf` jobs, each for 3bp. which will certainly crash your filesystem.

**Comment by George-du** [comment]
Hi, I will rerun this code using the  **_--chunkSize 1000000_** parameter.
