### ISSUE TITLE
Missing hal2mafMP.py file 

### ISSUE THREAD

**Issue by shameem356** [ComparativeGenomicsToolkit/hal#85]
I tried to install  hal ( V 2.1) and installed successfully. But hal2mafMP.py file is missing in bin folder. So I am not able to run Ragout software. Please can you let me know why this file is missing ? Here  is the [list of executable](https://wcmq.app.box.com/s/tr6zdfq3ie5r034a6yq1mcrtie7q98x4) which I found in bin folder .

**Comment by diekhans** [comment]
It is in maf/hal2mafMP.py.  Most likely a problem with a makefile not
copying it to bin, Just copy it by hand.

**Comment by shameem356** [comment]
Hello @diekhans ,

Thank you so much for your quick reply. Yes , I could find hal2mafMP.py in maf folder and copied to bin folder. Now I am facing another problem related to '**ImportError: No module named hal.stats.halStats**'

Traceback (most recent call last):
  File "/data/labs/genomics_lab/shared/apps/HAL/hal/bin/hal2mafMP.py", line 26, in <module>
    from hal.stats.halStats import runParallelShellCommands
ImportError: No module named hal.stats.halStats
Traceback (most recent call last):
  File "bin/ragout", line 32, in <module>
    sys.exit(main())
  File "/data/labs/genomics_lab/shared/apps/Ragout/ragout/main.py", line 290, in main
    _run_ragout(args)
  File "/data/labs/genomics_lab/shared/apps/Ragout/ragout/main.py", line 175, in _run_ragout
    args.threads)
  File "/data/labs/genomics_lab/shared/apps/Ragout/ragout/synteny_backend/synteny_backend.py", line 36, in make_permutations
    files = self.run_backend(recipe, output_dir, overwrite)
  File "/data/labs/genomics_lab/shared/apps/Ragout/ragout/synteny_backend/hal.py", line 103, in run_backend
    subprocess.check_call(cmdline, stdout=open(os.devnull, "w"))
  File "/usr/lib64/python2.7/subprocess.py", line 542, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['hal2mafMP.py', 'examples/hal_example/alignment.hal', 'example_out/hal-workdir/alignment.maf', '--noAncestors', '--numProc', '1', '--refGenome', 'h1', '--targetGenomes', 'o395,h1,inaba,biovar']' returned non-zero exit status 1
