### ISSUE TITLE
ImportError: No module named hal.stats.halStats

### ISSUE THREAD

**Issue by shameem356** [ComparativeGenomicsToolkit/hal#87]
I am getting the following error while running Ragout software. I already set up the python of hal. I am getting this error after solving this problem [#85](https://github.com/ComparativeGenomicsToolkit/hal/issues/85)

raceback (most recent call last):
File "/data/labs/genomics_lab/shared/apps/HAL/hal/bin/hal2mafMP.py", line 26, in
from hal.stats.halStats import runParallelShellCommands
**ImportError: No module named hal.stats.halStats**
Traceback (most recent call last):
File "bin/ragout", line 32, in
sys.exit(main())
File "/data/labs/genomics_lab/shared/apps/Ragout/ragout/main.py", line 290, in main
_run_ragout(args)
File "/data/labs/genomics_lab/shared/apps/Ragout/ragout/main.py", line 175, in _run_ragout
args.threads)
File "/data/labs/genomics_lab/shared/apps/Ragout/ragout/synteny_backend/synteny_backend.py", line 36, in make_permutations
files = self.run_backend(recipe, output_dir, overwrite)
File "/data/labs/genomics_lab/shared/apps/Ragout/ragout/synteny_backend/hal.py", line 103, in run_backend
subprocess.check_call(cmdline, stdout=open(os.devnull, "w"))
File "/usr/lib64/python2.7/subprocess.py", line 542, in check_call
raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['hal2mafMP.py', 'examples/hal_example/alignment.hal', 'example_out/hal-workdir/alignment.maf', '--noAncestors', '--numProc', '1', '--refGenome', 'h1', '--targetGenomes', 'o395,h1,inaba,biovar']' returned non-zero exit status 1

**Comment by diekhans** [comment]
hal2mafMP wants PYTHONPATH environment variable to be set to the
parent directory containing the directories sonLib and hal.

Sorry that this is a bit unfriendly

**Comment by amizeranschi** [comment]
Hi!

I'm getting a very similar error, when using Cactus and Ragout installed from Bioconda. 

Could you be a bit more explicit regarding what PYTHONPATH should be set to?

If it helps, I'm using Cactus's evolverMammals example:

```
[17:21:10] INFO: Starting Ragout v2.2
[17:21:10] INFO: Running withs synteny block sizes '[5000, 500, 100]'
[17:21:10] INFO: Extracting FASTA from HAL
[17:21:10] INFO: Converting HAL to MAF
Traceback (most recent call last):
  File "/export/home/ncit/external/a.mizeranschi/cactus_conda/anaconda/bin/hal2mafMP.py", line 25, in <module>
    from hal.stats.halStats import runParallelShellCommands
ImportError: No module named hal.stats.halStats
Traceback (most recent call last):
  File "/export/home/ncit/external/a.mizeranschi/ragout_conda/anaconda/bin/ragout", line 32, in <module>
    sys.exit(main())
  File "/export/home/ncit/external/a.mizeranschi/ragout_conda/anaconda/lib/python2.7/site-packages/ragout/main.py", line 290, in main
    _run_ragout(args)
  File "/export/home/ncit/external/a.mizeranschi/ragout_conda/anaconda/lib/python2.7/site-packages/ragout/main.py", line 175, in _run_ragout
    args.threads)
  File "/export/home/ncit/external/a.mizeranschi/ragout_conda/anaconda/lib/python2.7/site-packages/ragout/synteny_backend/synteny_backend.py", line 36, in make_permutations
    files = self.run_backend(recipe, output_dir, overwrite)
  File "/export/home/ncit/external/a.mizeranschi/ragout_conda/anaconda/lib/python2.7/site-packages/ragout/synteny_backend/hal.py", line 103, in run_backend
    subprocess.check_call(cmdline, stdout=open(os.devnull, "w"))
  File "/export/home/ncit/external/a.mizeranschi/ragout_conda/anaconda/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['hal2mafMP.py', 'evolverMammals.hal', 'ragout-out/hal-workdir/alignment.maf', '--noAncestors', '--numProc', '20', '--refGenome', 'simMouse_chr6', '--targetGenomes', 'simMouse_chr6,simCow_chr6,simHuman_chr6,simDog_chr6,simRat_chr6']' returned non-zero exit status 1
```
